# flake8: noqa: B950
# fmt: off
# This file was generated by AutoHeuristic. Do not modify it manually!
# To regenerate this file, take a look at the steps in the README.md file inside torchgen/_autoheuristic/async_tp_tile_config/
from typing import Optional

from torch._inductor.autoheuristic.autoheuristic_utils import (
    AHContext,
    AHMetadata,
    Choice,
)
from torch._inductor.autoheuristic.learnedheuristic_interface import (
    LearnedHeuristicDecision,
)


class AsyncTPTileConfigH100(LearnedHeuristicDecision):

    def __init__(self) -> None:
        self.choices: list[Choice] = []
        self.fill_choices()

    def check_precondition(self, metadata: AHMetadata, context: AHContext,) -> bool:
        return (
            metadata.name == self.get_name()
            and metadata.shared_memory == 232448
            and str(metadata.device_capa) == "(9, 0)"
        )

    def get_confidence_threshold(self) -> float:
        return 0.0

    def get_choice(self, idx: int) -> Optional[str]:
        if idx < len(self.choices):
            return self.choices[idx]
        return None

    def fill_choices(self) -> None:
        self.choices.append('T128x128_C2x1')
        self.choices.append('T128x256_C1x1')
        self.choices.append('T128x256_C2x1')
        self.choices.append('T128x64_C1x1')
        self.choices.append('T128x64_C1x2')
        self.choices.append('T128x64_C2x1')
        self.choices.append('T64x128_C1x1')
        self.choices.append('T64x128_C1x2')
        self.choices.append('T64x128_C2x1')
        self.choices.append('T64x64_C1x1')
        self.choices.append('T64x64_C2x1')

    def get_name(self) -> str:
        return 'async_tp_tile_config'

    def get_best_choices(self, context: AHContext) -> Optional[list[tuple[float, int]]]:
        if context.get_value('m_times_n') <= 7602176.0:
            if context.get_value('arith_intensity') <= 644.023193359375:
                if context.get_value('m_times_n') <= 1998848.0:
                    return [(0.667, 7), (0.333, 9)]
                else:
                    return [(0.500, 6), (0.500, 10)]
            else:
                if context.get_value('m_times_k') <= 12058624.0:
                    return [(0.500, 4), (0.250, 3), (0.250, 8)]
                else:
                    return [(1.000, 5)]
        else:
            if context.get_value('n') <= 3648.0:
                if context.get_value('m') <= 12288.0:
                    return [(1.000, 0)]
                else:
                    return [(0.500, 1), (0.500, 2)]
            else:
                return [(1.000, 2)]
